spring:
  datasource:
    url: jdbc:h2:./blogappdb
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
app:
  jwt:
    secretKey: 5aedf332sakdsafd5aedf3dasdasfd
    issuer: MehmetKicirti